const images = {
    logo: '/assets/images/logo.jpg',
    // scholars
    imamabuhanifa: '/assets/scholars/imamabuhanifa.png',
    imamahmadibnhanbal: '/assets/scholars/imamahmadibnhanbal.png',
    imamtabari: '/assets/scholars/imamtabari.png',
    imammalikibnanas: '/assets/scholars/imammalikibnanas.png',
    imamibnmajah: '/assets/scholars/imamibnmajah.png',
    imamtirmidhi: '/assets/scholars/imamtirmidhi.png',
    imammuslimibnalhajjaj: '/assets/scholars/imammuslimibnalhajjaj.png',
    imammuhammadalbukhari: '/assets/scholars/imammuhammadalbukhari.png',
    imamabudawood: '/assets/scholars/imamabudawood.png',
    sheikhnasirassadi: '/assets/scholars/sheikhnasirassadi.jpg',
    sheikhbinbaz: '/assets/scholars/sheikhbinbaz.jpg',
    sheikhuthaymeen: '/assets/scholars/sheikhuthaymeen.jpg',
    sheikhalbani: '/assets/scholars/sheikhalbani.jpg',
    sheikhfawzan: '/assets/scholars/sheikhfawzan.jpg',
    sheikhruhayli: '/assets/scholars/sheikhruhayli.jpg',
    loading: '/assets/images/svg/loading.svg',
    bismillah: '/assets/images/bismillah.png',
    makkah: '/assets/images/makkah.png',
    madinah: '/assets/images/madinah.png',
    lailahaillallah: '/assets/images/lailahaillallah.png',
    bannerBG: '/assets/images/bannerBG.jpg',
    quranayah: '/assets/images/quranayah.jpg',
    bg: '/assets/images/bg.jpg',
    prayerbg: '/assets/images/prayerbg.png',
}
export default images;